/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container':        '#fc6b34',
        'surface-container-high':     '#eae8e7',
        'surface':                    '#fbf9f8',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f6f3f2',
        'surface-container':          '#f0eded',
        'surface-dim':                '#dcd9d9',
        'surface-variant':            '#e4e2e1',
        'surface-bright':             '#fbf9f8',
        'on-surface':                 '#1b1c1c',
        'on-surface-variant':         '#47464f',
        'on-background':              '#1b1c1c',
        'outline':                    '#777680',
        'outline-variant':            '#c8c5d0',
        'primary':                    '#020037',
        'primary-container':          '#1a1a4e',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#8383bd',
        'secondary':                  '#aa3700',
        'secondary-fixed':            '#ffdbcf',
        'on-secondary':               '#ffffff',
        'on-secondary-fixed':         '#380c00',
        'on-secondary-fixed-variant': '#822800',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
        'inverse-surface':            '#303030',
        'inverse-on-surface':         '#f3f0f0',
        'inverse-primary':            '#c1c1ff',
        'background':                 '#fbf9f8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
      },
      fontFamily: {
        headline: ['"Work Sans"', 'sans-serif'],
        body:     ['"Public Sans"', 'sans-serif'],
        label:    ['"Public Sans"', 'sans-serif'],
      },
    },
  },
};
